// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qubeovprtqeaassyasst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1YmVvdnBydHFlYWFzc3lhc3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODMzNTYsImV4cCI6MjA2NTY1OTM1Nn0.7FyNeswKdCP7eU5unpjJdTqz7Rv_oawycfH71uWj32M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);